# Generated by Django 4.1.1 on 2022-09-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.TextField()),
                ('telefono', models.CharField(max_length=9)),
                ('sexo', models.TextField()),
                ('cumpleaño', models.DateTimeField()),
                ('dia_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
